#!/bin/sh

echo loading RT Linux if needed...
../insrtl 2> /dev/null || exit 1

echo loading RT task...
sudo rmmod variable_task 2> /dev/null
sudo insmod variable_task.ko || exit 1

echo waiting 10 seconds...
sleep 10

echo removing RT task...
sudo rmmod variable_task

echo done

exit 0
